// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFjcFbr1496zw2Wd5Mo0_cpa9Ej1-YWHA',
    appId: '1:524519313:web:69a1e627ba3f7a7e4e3c30',
    messagingSenderId: '524519313',
    projectId: 'todoapp-2a2a5',
    authDomain: 'todoapp-2a2a5.firebaseapp.com',
    storageBucket: 'todoapp-2a2a5.appspot.com',
    measurementId: 'G-N09Z6WP37B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOSdZWGrf9tGyT9E5Mhovzc0GczwjvRrM',
    appId: '1:524519313:android:c2a057c09ea1fd674e3c30',
    messagingSenderId: '524519313',
    projectId: 'todoapp-2a2a5',
    storageBucket: 'todoapp-2a2a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALPxzCPZLEmX-9MmAEdP6bI87N6Q5XN7Y',
    appId: '1:524519313:ios:561f00f6ffdd38734e3c30',
    messagingSenderId: '524519313',
    projectId: 'todoapp-2a2a5',
    storageBucket: 'todoapp-2a2a5.appspot.com',
    iosClientId: '524519313-qgbeihpn1qf6sfaurb26dvi4e8sl7r8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALPxzCPZLEmX-9MmAEdP6bI87N6Q5XN7Y',
    appId: '1:524519313:ios:561f00f6ffdd38734e3c30',
    messagingSenderId: '524519313',
    projectId: 'todoapp-2a2a5',
    storageBucket: 'todoapp-2a2a5.appspot.com',
    iosClientId: '524519313-qgbeihpn1qf6sfaurb26dvi4e8sl7r8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
